---

- name: Install nginx
  package:
    name: nginx
    state: present

- name: Add configuration file
  template:
    src: server.conf.j2
    dest: /etc/nginx/conf.d/server.conf
  notify: Restart nginx

- name: Ensure service is enabled
  service:
    name: nginx
    enabled: yes
